#SPDX-License-Identifier: MIT-0
---
# tasks file for nodejs
- name: "Add nodejs 22.x ppa for apt repo"
  shell: curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
- name: "install node"
  shell: apt-get install -y nodejs
- name: "install yarn"
  shell: npm install -g yarn
