#SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Install aptitude
  become: true
  apt:
    name: aptitude
    state: latest
    update_cache: true
- name: Install curl
  become: true
  apt:
    name: curl
    state: present
- name: Install wget
  become: true
  apt:
    name: wget
    state: present
- name: Install required system packages
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - rsync
    state: latest
    update_cache: true
- name: Check if swap file exists
  become: true
  stat:
    path: /swapfile
  register: swap_file
- name: Create swap file
  become: true
  command: fallocate -l 2G /swapfile
  when: not swap_file.stat.exists
- name: Set swap file permissions
  become: true
  file:
    path: /swapfile
    mode: '0600'
  when: not swap_file.stat.exists
- name: Format swap file
  become: true
  command: mkswap /swapfile
  when: not swap_file.stat.exists
- name: Enable swap
  become: true
  command: swapon /swapfile
  when: not swap_file.stat.exists
- name: Make swap permanent
  become: true
  lineinfile:
    path: /etc/fstab
    line: '/swapfile none swap sw 0 0'
    state: present
