#SPDX-License-Identifier: MIT-0
---
# tasks file for nextjs_app
# ? Might need to cd first
- name: install deps
  shell: yarn install 
- name: build app
  shell: yarn build
# TODO: Change this build to allow serverside logic
- name: run app
  shell: node ./.next/standalone/server.js
