#SPDX-License-Identifier: MIT-0
---
# tasks file for nextjs_app
# ? Might need to cd first
- name: install deps
  shell: yarn install 
- name: build app
  shell: yarn build
# TODO: Change this to use pm2?
- name: run app
  shell: yarn start
